# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57fa8bfbfa106c770f51dc906eef85b8e7fa1cb645d8fb13e825b349583edf40e593a58619548d04d501481fc610a3cb8edb2c243ab60202ef9e9429916232aa

test:
  secret_key_base: d8a063d09ad50d9632bff014fdaeba92c10a1e9935a33b5007bf4b4bc36c4f5ca1b6d0238acc53ba9696c69187419029f3477d078b30b69e6907122caa194f59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
