# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5603ae1775596d3f33782901725c427022f9ec70f268c7c00a7ca9eadd74ca9e24a1d4f2a83a4cd8c39c2edfc39e1b3ab1ae05858be142af96e9d4c43851dbbc

test:
  secret_key_base: fd63db58238e4b73473bb39fa42047ec1e2c1c373e3448d3af09ab454faceac16fd1d536c043cc580acee0b83288f4af7d06ed335ffe246412629e7a763d4f88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
